# AWS RDS MySQL
spring.datasource.url=jdbc:mysql://database-1.cpeu8gaaamv6.ap-northeast-2.rds.amazonaws.com:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=cicd1234!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false